name: Docker Build and Push

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Debugging step: Check if Docker username is correctly passed
      - name: Check Docker Username
        run: echo "Docker Username: ${{ secrets.DOCKER_USERNAME }}"

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t sasideva/blogmicroservices:latest .

      - name: Push Docker Image
        run: docker push sasideva/blogmicroservices:latest
