name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}  
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .  
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/blogmicroservices:latest # Using "latest" tag for simplicity

    - name: Log out from Docker Hub
      run: docker logout

    - name: Notify Success
      if: success() # Sends a success message if all previous steps succeed
      run: echo "Docker image has been built and pushed successfully!"

